SELECT * FROM linkedin.appdata2;

# 1.Which apps have the highest rating in the given available dataset?

SELECT app, rating
FROM 
linkedin.appdata2
order by reviews desc
limit 10;

# 2.What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.
SELECT app,installs,reviews
FROM
linkedin.appdata2
ORDER BY reviews desc
limit 10;

# 3.Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
SELECT app,reviews,category
FROM
linkedin.appdata2
ORDER BY Reviews DESC;

/*4.What is the total amount of revenue generated by the google play store by hosting apps? 
(Whenever a user buys apps  from the google play store, the amount is considered in the revenue)*/

SELECT sum(revenue) as total_revenue
FROM
linkedin.appdata2


/*5.Which Category of google play store apps has the highest number of installs?
 also, find out the total number of installs for 
that particular category.*/

SELECT category, installs
FROM 
linkedin.appdata2
GROUP BY Category
ORDER BY installs DESC;

/* 6.Which Genre has the most number of published apps?*/
SELECT genres, count(app) AS Number_of_apps
FROM 
linkedin.appdata2
GROUP BY Genres
ORDER BY count(app) desc;

/* 7.Provide the list of all games ordered in such a way that the game 
that has the highest number of installs is displayed on the top*/
SELECT DISTINCT app, installs
FROM 
linkedin.appdata2
WHERE Category='game'
ORDER BY installs desc;

/*8.Provide the list of apps that can work on android version 4.0.3 and UP*/
SELECT DISTINCT app
FROM
linkedin.appdata2
WHERE 
Android_Ver='4.0.3 and UP';

/*9.How many apps from the given data set are free? 
Also, provide the number of paid apps*/

SELECT count(app='free') as free_apps, count(app='paid') as paid_apps
FROM
linkedin.appdata2 
where Type='free';

/*10.Which is the best dating app? 
(Best dating app is the one having the highest number of Reviews)*/

SELECT app
FROM
linkedin.appdata2
WHERE Category='dating'
ORDER BY Reviews desc
limit 1;

/*11.Get the number of reviews having positive sentiment and 
number of reviews having negative sentiment for the app 10 best foods for you and compare them*/
SELECT COUNT(sentiment='positive') as positive_review, 
COUNT(sentiment='negative') as negative_review
FROM
linkedin.appdata2
WHERE
category='Food'
LIMIT 10;

/* 12.which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?*/

SELECT translated_review
FROM
linkedin.appdata2
WHERE app='ASUS SuperNote' AND sentiment_polarity='1' AND sentiment_subjective='1';

/* 13.Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat*/
SELECT translated_review
FROM
linkedin.appdata2
WHERE app='Abs Training-Burn belly fat'
AND sentiment='Neutral';

/* 14.Extract all negative sentiment reviews for Adobe Acrobat 
Reader with their sentiment polarity and sentiment subjectivity*/
SELECT translated_review, sentiment polarity,
sentiment subjectivity
FROM 
linkedin.appdata2
WHERE app='Adobe Acrobat' AND sentiment = 'negative';



